#!/bin/bash

cd "`dirname \"$0\"`"
cd ..

SUFFIX="$1"

mkdir -p apks
cp `.travis/release-apk` apks/
cp `.travis/debug-apk` apks/

cd apks

for apk in *; do
    new_apk="fruit-radar$SUFFIX`echo \"$apk\" | sed \"s/app//g\"`"
    if [ "$new_apk" != "$apk" ]; then
        mv "$apk" "$new_apk"
        echo "$new_apk"
    fi
done

