#!/bin/bash

set -e

cd "`dirname \"$0\"`"

# Set up git user name and tag this commit
# from https://docs-staging.travis-ci.com/user/deployment/releases/
git config --local user.name "Travis-CI"
git config --local user.email "mundraub-android@travis-ci.org"

cd ..
git add app/src/main/res/values*
git commit -m"updated languages" || true

# create the git tag
version="`./next_version`"
echo "Version: $version"
git tag "$version"

