#!/bin/bash

set -e

cd "`dirname \"$0\"`"

RUN_ONCE=".create_tag_done"

if [ "$CI" == "true" ]; then
  echo "Running on Travis-CI."
  if [ -e "$RUN_ONCE" ]; then
    echo "Travis has already created a tag `./latest_version`. Nothing to do."
    exit 0
  fi
  touch "$RUN_ONCE"
fi

# Set up git user name and tag this commit
# from https://docs-staging.travis-ci.com/user/deployment/releases/
git config --local user.name "Travis-CI"
git config --local user.email "mundraub-android@travis-ci.org"

(
  cd ..
  git add app/src/main/res/values*
  git status
  git commit -m"updated languages" || true
)

# create the git tag
version="`./next_version`"
echo "Version: $version"
git tag "$version"

