#!/bin/bash
#
# This script creates the meta data for Google Play
#

cd "`dirname \"$0\"`"
cd ..

METADATA_OUTPUT="$1"
METADATA_SOURCE="./metadata"
# These are all the languages compatible with Google Play
LANGUAGES="de-DE en-US fr-FR ru-RU af am ar hy-AM az-AZ eu-ES bn-BD my-MM bg zh-HK zh-TW zh-CN da-DK en-IN en-SG en-ZA en-AU en-CA en-GB et fil fi-FI fr-CA gl-ES ka-GE el-GR iw-IL hi-IN id is-IS it-IT ja-JP kn-IN kk ca km-KH ky-KG ko-KR hr lo-LA lv lt ms ms-MY ml-IN mr-IN mk-MK mn-MN ne-NP nl-NL no-NO fa fa-AE fa-AF fa-IR pl-PL pt-BR pt-PT pa rm ro sv-SE sr si-LK sk sl es-419 es-ES es-US sw ta-IN te-IN th cs-CZ tr-TR uk hu-HU vi be zu "

rm -rf "$METADATA_OUTPUT"
mkdir -p "$METADATA_OUTPUT"
for language in $LANGUAGES; do
    short_language=`echo "$language" | grep -oE '^[a-zA-Z]+'`
    if [ "$short_language" != "$language" ] && [ -d "$METADATA_SOURCE/$short_language" ]; then
        echo "copy $short_language into $language"
        mkdir -p "$METADATA_OUTPUT/$language"
        cp -r -t "$METADATA_OUTPUT/$language" "$METADATA_SOURCE/$short_language/"*
    fi
    if [ -d "$METADATA_SOURCE/$language" ]; then
        echo "copy $language into $language"
        mkdir -p "$METADATA_OUTPUT/$language"
        cp -r -t "$METADATA_OUTPUT/$language" "$METADATA_SOURCE/$language/"*
    fi
    full_description="$METADATA_OUTPUT/$language/full_description.txt"
    full_description_play="$METADATA_OUTPUT/$language/full_description_play.txt"
    if [ -f "$full_description_play" ]; then
        if [ -f "$full_description" ]; then
            (
                echo 
                cat "$full_description_play"
            ) >> "$full_description"
        fi
        rm "$full_description_play"
    fi
done
