#!/bin/bash

set -e

# arguments
TRACK="$1"

# constants
HERE="`dirname \"$0\"`"
APK="$HERE/../apks/fruit-radar-google-play-release.apk"

cd "$HERE"

if ! which fastlane > /dev/null; then
    echo "fastlane is not installed. It will be installed now."
    (
        cd ..
        gem install bundler
        bundle install
    )
fi

if ! [ -f "$APK" ]; then
    echo "ERROR: expected file: $APK"
    echo "       This script assumes that you have run the file"
    echo "       `dirname \"$0\"`/create-google-play-release and there"
    echo "       is a file named 'fruit-radar-google-play-release.apk'"
    echo "       in the 'apks' folder."
    exit 1
fi

fastlane supply --track "$TRACK" --apk "$APK"

