#!/bin/bash
#
# This shows the next version but does not create the tag.
#

cd "`dirname \"$0\"`"

this_version="`./latest_version`"
minor_version="`echo \"$this_version\" | grep -oE '[0-9]+$'`"
prefix="`echo \"$this_version\" | grep -oE '^v[0-9]+\.'`"

# echo next version
echo -n "$prefix$(($minor_version + 1))"

