#!/bin/bash
#
# Make the app aware about the current commit.
#

set -e

cd "`dirname \"$0\"`"

file="../app/src/main/java/eu/quelltext/mundraub/Settings.java"

echo "Editing `dirname \"$0\"`/$file"

hash="`git rev-parse --verify HEAD`"

echo "Set COMMIT_HASH=\"$hash\""

sed -ri 's/(COMMIT_HASH\s+=\s+)INVALID_HASH/\1"'"$hash"'"/g' "$file"


